CREATE TABLE CUSTOMER (
	id INT AUTO_INCREMENT PRIMARY KEY,
	type_id VARCHAR(250),
	document_id VARCHAR(250),
	first_name VARCHAR(250),
	last_name VARCHAR(250),
	phone VARCHAR(250),
	address VARCHAR(250),
	email VARCHAR(250)
);
